site:
  baseline: Everyone's doing it
  baseurl: /
  canonicalurl: true
  date:
    format: j F Y
    timezone: Europe/Paris
  description: Design blog powered by ZDesign
  netlify:
    cms:
      path: admin
      version: latest
    identity:
      version: v1
  pagination:
    max: 5
    path: page
  title: ZDesign Blog
theme: hyde
